### PR TITLE
Add screen share to developer tools, similiar to webchat

### PR DESCRIPTION
**Pull request by jensengar**

### CODE REVIEW

**Comment by jensengar** [comment]
Screen Shot 2019-03-26 at 8 56 42 AM
Screen Shot 2019-03-26 at 8 56 50 AM
Screen Shot 2019-03-26 at 8 56 56 AM
Screen Shot 2019-03-26 at 8 57 06 AM

**Comment by PrinceNebulon** [comment]
@xdumaine is this good from your perspective?

**Comment by xdumaine** [comment]
One change: `contentCssUrl` should show always, not just when `standalone` is `No`

**Comment by xdumaine** [comment]
After that, 👍

**Comment by jensengar** [comment]
Done.

**Pull request merged**
